/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package producto;
import javax.swing.JOptionPane;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import java.sql.ResultSet;
/**
 *
 * @author rober
 */
public class frm_pdf extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_pdf
     */
    public frm_pdf() {
        initComponents();
   con.setURL("C:\\textos\\bodega.db");
    }
    conecto_sql.Conecto_sql con=new conecto_sql.Conecto_sql();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jButton1.setText("PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       ResultSet rs;
       int l=1;
        try{
            PDDocument documento=new PDDocument();
            PDPage pagina =new PDPage(PDRectangle.A6);
            
            documento.addPage(pagina);
            
            PDPageContentStream contenido=new PDPageContentStream(documento,pagina);
            
            con.Abrir();
                rs=con.Seleccionar("select * from productos ");
                          
             while(rs.next()){
                contenido.beginText();
                contenido.setFont(PDType1Font.COURIER,12);
                contenido.newLineAtOffset(20, pagina.getMediaBox().getHeight()-(20*l));
                l++;
              //  contenido.showText(rs.getString("id_prod")+"\t | "+rs.getString("nom_prod"));
                contenido.showText(rs.getString("id_prod")+"   |"+rs.getString("nom_prod"));
                   contenido.endText();         
             }
             
            con.Cerrar();    
            
            contenido.close();
            
            documento.save("C:\\textos\\pdf.pdf");
            JOptionPane.showMessageDialog(this, "creado");
            
        }
        catch(Exception x){
            System.out.println("error"+x.getMessage().toString());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
